version: "3.3"
services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
  redis:
    image: "redis:alpine"

  db:
    image: postgres:15
    restart: always
    container_name: improvs_test_task_dbcontainer
    environment:
      POSTGRES_DB: improvs_test_task_dev
      POSTGRES_USER: improvs_test_task_dev
      POSTGRES_PASSWORD: improvs_test_task_dev
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    ports:
      - "5432:5432"


    volumes:
      - ./custom_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
